# Generated by Django 5.1.7 on 2025-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('alary_currency', models.CharField(max_length=20)),
                ('alternate_url', models.URLField()),
                ('snippet_requirement', models.TextField()),
                ('snippet_responsibility', models.TextField()),
                ('schedule_name', models.TextField(max_length=300)),
                ('employer_name', models.CharField(max_length=500)),
                ('employer_alternate_url', models.CharField(max_length=500)),
                ('employer_raiting', models.PositiveIntegerField()),
                ('employer_review_count', models.PositiveIntegerField()),
                ('area_name', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('created_record', models.DateTimeField(auto_now_add=True)),
                ('update_record', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
