# Generated by Django 5.1.7 on 2025-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundvacancies',
            old_name='alary_currency',
            new_name='salary_currency',
        ),
        migrations.AddField(
            model_name='foundvacancies',
            name='search_request',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('data analyst', 'data analyst'), ('data engineer', 'data engineer')], default='django', max_length=20),
        ),
    ]
