# Generated by Django 5.1.7 on 2025-03-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0002_rename_alary_currency_foundvacancies_salary_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundvacancies',
            name='employer_responded',
            field=models.BooleanField(default=False),
        ),
    ]
