# Generated by Django 5.1.7 on 2025-03-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0003_foundvacancies_employer_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundvacancies',
            name='employer_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
