# Generated by Django 5.1.7 on 2025-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0004_foundvacancies_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundvacancies',
            name='salary_from',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundvacancies',
            name='salary_to',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
