# Generated by Django 5.1.7 on 2025-03-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0005_alter_foundvacancies_salary_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundvacancies',
            old_name='employer_raiting',
            new_name='employer_rating',
        ),
    ]
