# Generated by Django 5.1.7 on 2025-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0006_rename_employer_raiting_foundvacancies_employer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundvacancies',
            name='employer_rating',
            field=models.FloatField(),
        ),
    ]
