# Generated by Django 5.1.7 on 2025-04-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0008_usertokenmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundvacancies',
            options={'ordering': ['employer_rating', 'employer_review_count', '-published_at']},
        ),
        migrations.AddField(
            model_name='foundvacancies',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foundvacancies',
            name='negotiations',
            field=models.BooleanField(default=False),
        ),
    ]
