# Generated by Django 5.2 on 2025-04-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0010_alter_foundvacancies_snippet_requirement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundvacancies',
            options={'ordering': ['-employer_rating', '-employer_review_count', '-published_at']},
        ),
    ]
