# Generated by Django 5.2 on 2025-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0011_alter_foundvacancies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundvacancies',
            name='search_request',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('data analyst', 'data analyst'), ('data engineer', 'data engineer'), ('airflow', 'airflow')], default='django', max_length=20),
        ),
    ]
