# Generated by Django 5.2 on 2025-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0012_alter_foundvacancies_search_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('search_request', models.CharField(max_length=20)),
                ('resume_id', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
