# Generated by Django 5.2 on 2025-04-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_search', '0013_resumeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundvacancies',
            name='search_request',
            field=models.CharField(choices=[('django', 'django'), ('airflow', 'airflow'), ('data engineer', 'data engineer'), ('data analyst', 'data analyst'), ('python', 'python')], default='django', max_length=20),
        ),
    ]
